### ISSUE TITLE
build_stage2.sh failing "undefined symbol: soup_server_listen_all"

### ISSUE THREAD

**Issue by praveenkumar** [CentOS/sig-atomic-buildscripts#153]
I was trying to create atomic bits as suggested in readme but it I am getting a strange error. I tried to debug it but no success. 

```
# bash -x ./build_stage2.sh /srv
++ date +%Y%m%d
+ VERSION=7.20160911
++ date +%Y%m%d_%H%M%S
+ DateStamp=20160911_055713
++ pwd
+ GitDir=/root/work/github/sig-atomic-buildscripts
+ BuildDir=/srv
+ LogFile=/srv/log
+ mkdir -p /srv
++ cd /srv
++ pwd
+ BuildDir=/srv
+ OstreeRepoDir=//srv/repo
+ mkdir -p //srv/repo
+ ln -s //srv/repo /srv/repo
ln: failed to create symbolic link ‘/srv/repo/repo’: File exists
+ set -x
+ set -e
+ set -o pipefail
+ cd /srv
+ systemctl start docker
+ systemctl start libvirtd
+ echo '---------- installer '
+ rpm-ostree-toolbox installer --overwrite --ostreerepo /srv/repo -c /root/work/github/sig-atomic-buildscripts/config.ini -o /srv/installer
+ tee /srv/log
workdir=/tmp/atomic-treecomposefjmljN.tmp
rpmostree_cache_dir=None
pkgdatadir=/usr/share/rpm-ostree-toolbox
os_name=centos-atomic-host
ostree_remote=centos-atomic-host
os_pretty_name=MyCustom CentOS Atomic Host
ostree_repo=/srv/repo
tree_name=standard
tree_file=/home/work/github/sig-atomic-buildscripts/centos-atomic-host.json
arch=x86_64
release=7
ref=centos-atomic-host/7/x86_64/standard
yum_baseurl=http://mirror.centos.org/centos/7/os/x86_64/
lorax_additional_repos=http://mirror.centos.org/centos/7/updates/x86_64/, http://buildlogs.centos.org/centos/7/atomic/x86_64/Packages/, http://cbs.centos.org/repos/atomic7-testing/x86_64/os/
is_final=True
lorax_inherit_repos=None
lorax_exclude_packages=oscap-anaconda-addon
lorax_include_packages=None
lorax_rootfs_size=None
local_overrides=None
http_proxy=None
selinux=True
configdir=/home/work/github/sig-atomic-buildscripts
docker_os_name=mirror.centos.org/centos7-atomic-builder
vsphere_product_name=None
vsphere_product_vendor_name=None
vsphere_product_version=None
vsphere_virtual_system_type=None
ostree: symbol lookup error: ostree: undefined symbol: soup_server_listen_all
Traceback (most recent call last):
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 75, in <module>
    main()
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 59, in main
    installer.main(cmd)
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/installer.py", line 256, in main
    composer.create(post=args.post)
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/taskbase.py", line 495, in create
    self.impl_create(**kwargs)
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/installer.py", line 162, in impl_create
    httpd_port = str(trivhttp.http_port)
AttributeError: 'TrivialHTTP' object has no attribute 'http_port'

# rpm -qa | grep ostree
rpm-ostree-toolbox-2016.4-1.el7.centos.x86_64
rpm-ostree-2016.5-1.atomic.el7.x86_64
ostree-2016.7-2.atomic.el7.x86_64
ostree-fuse-2016.7-2.atomic.el7.x86_64

# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
```

**Comment by cgwalters** [comment]
`ostree: undefined symbol: soup_server_listen_all` is kind of fatal here - try doing a `yum update libsoup` ?

**Comment by kbsingh** [comment]
@praveenkumar can you also confirm what repo/branch you are building here and your CentOS-7 machine is completely updated ?

**Comment by praveenkumar** [comment]
So updating `libsoup` did trick for me and able to build images locally.
