### ISSUE TITLE
Missing newer continuous images

### ISSUE THREAD

**Issue by jlebon** [CentOS/sig-atomic-buildscripts#193]
Seems like something happened to the every-6-hour job that creates images from the latest continuous tree. E.g. the latest at https://ci.centos.org/artifacts/sig-atomic/centos-continuous/images/cloud/latest/images/ dates from Nov 15th.

**Comment by miabbott** [comment]
From https://ci.centos.org/job/atomic-cahc-image-cloud-continuous/776/console

```
17:25:09 + sudo rpm-ostree-toolbox imagefactory -c /home/builder/sig-atomic-buildscripts/config.ini --ostreerepo http://artifacts.ci.centos.org/sig-atomic/rdgo/centos-continuous/ostree/repo -i kvm -i vagrant-libvirt -i vagrant-virtualbox --preserve-ks-url --tdl /home/builder/sig-atomic-buildscripts/cahc.tdl -k /home/builder/sig-atomic-buildscripts/cloud.ks --vkickstart /home/builder/sig-atomic-buildscripts/vagrant.ks -o 7.2016.1086 --overwrite
17:25:10 Traceback (most recent call last):
17:25:10   File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 23, in <module>
17:25:10     from rpmostreecompose import taskrunner, version, liveimage, docker_image
17:25:10   File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/taskrunner.py", line 28, in <module>
17:25:10     gi.require_version('GSystem', '1.0')
17:25:10   File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 81, in require_version
17:25:10     raise ValueError('Namespace %s not available' % namespace)
17:25:10 ValueError: Namespace GSystem not available
```

...which looks similar to projectatomic/rpm-ostree-toolbox#104

An updated r-o-t on the CI slaves would fix this, I think.
