### ISSUE TITLE
cloud-init fails to start in latest CAHC image

### ISSUE THREAD

**Issue by jlebon** [CentOS/sig-atomic-buildscripts#290]
From an OpenStack cloud I see:

```
[    6.114827] cloud-init[677]: Traceback (most recent call last):
[    6.117034] cloud-init[677]: File "/usr/bin/cloud-init", line 618, in <module>
[    6.117882] cloud-init[677]: sys.exit(main())
[    6.119175] cloud-init[677]: File "/usr/bin/cloud-init", line 614, in main
[    6.121191] cloud-init[677]: get_uptime=True, func=functor, args=(name, args))
[    6.123276] cloud-init[677]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1875, in log_time
[    6.125185] cloud-init[677]: ret = func(*args, **kwargs)
[    6.126703] cloud-init[677]: File "/usr/bin/cloud-init", line 448, in status_wrapper
[    6.129037] cloud-init[677]: util.ensure_dirs((data_d, link_d,))
[    6.130184] cloud-init[677]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1253, in ensure_dirs
[    6.133032] cloud-init[677]: ensure_dir(d, mode)
[    6.134379] cloud-init[677]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1289, in ensure_dir
[    6.136700] cloud-init[677]: os.makedirs(path)
[    6.138190] cloud-init[677]: File "/usr/lib64/python2.7/os.py", line 150, in makedirs
[    6.140191] cloud-init[677]: makedirs(head, mode)
[    6.142206] cloud-init[677]: File "/usr/lib64/python2.7/os.py", line 157, in makedirs
[    6.144110] cloud-init[677]: mkdir(name, mode)
[[1;31mFAILED[0m] Failed to start Initial cloud-init job (pre-networking).
See 'systemctl status cloud-init-local.service' for details.
[[1;33mDEPEND[0m] Dependency failed for Cloud-config availability.
[    6.149339] cloud-init[677]: OSError: [Errno 30] Read-only file system: '/var/lib/cloud'
[[1;33mDEPEND[0m] Dependency failed for Execute cloud user/final scripts.
[[1;33mDEPEND[0m] Dependency failed for Apply the settings specified in cloud-config.
         Starting Initial cloud-init job (metadata service crawler)...
[    6.889503] cloud-init[1234]: Traceback (most recent call last):
[    6.892045] cloud-init[1234]: File "/usr/bin/cloud-init", line 618, in <module>
[    6.893034] cloud-init[1234]: sys.exit(main())
[    6.894173] cloud-init[1234]: File "/usr/bin/cloud-init", line 614, in main
[    6.896182] cloud-init[1234]: get_uptime=True, func=functor, args=(name, args))
[    6.898190] cloud-init[1234]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1875, in log_time
[    6.900190] cloud-init[1234]: ret = func(*args, **kwargs)
[    6.903034] cloud-init[1234]: File "/usr/bin/cloud-init", line 448, in status_wrapper
[    6.904282] cloud-init[1234]: util.ensure_dirs((data_d, link_d,))
[    6.906447] cloud-init[1234]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1253, in ensure_dirs
[    6.908276] cloud-init[1234]: ensure_dir(d, mode)
[    6.910375] cloud-init[1234]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1289, in ensure_dir
[    6.912314] cloud-init[1234]: os.makedirs(path)
[    6.914185] cloud-init[1234]: File "/usr/lib64/python2.7/os.py", line 150, in makedirs
[    6.916191] cloud-init[1234]: makedirs(head, mode)
[    6.917610] cloud-init[1234]: File "/usr/lib64/python2.7/os.py", line 157, in makedirs
[    6.919747] cloud-init[1234]: mkdir(name, mode)
[    6.921419] cloud-init[1234]: OSError: [Errno 30] Read-only file system: '/var/lib/cloud'
[[1;31mFAILED[0m] Failed to start Initial cloud-init job (metadata service crawler).
See 'systemctl status cloud-init.service' for details.
```

Haven't debugged much further yet.

**Comment by mike-nguyen** [comment]
On CAHC, I started at `7.2017.574` and upgraded to `7.2017.575` and the filesystem became read only.  The package change was
```
# rpm-ostree deploy 7.2017.575
Resolving version '7.2017.575'
2 metadata, 0 content objects fetched; 576 B transferred in 0 seconds
20 metadata, 0 content objects fetched; 5 KiB transferred in 1 seconds
 
2 delta parts, 3 loose fetched; 79369 KiB transferred in 7 seconds                                                    
Copying /etc changes: 25 modified, 4 removed, 48 added
Transaction complete; bootconfig swap: yes deployment count change: 0
Upgraded:
  ostree 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.a9cba0754ce8d81098afa850b25354634c28720c.el7.centos -> 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.c4dd042961eed840d10a08388d7a3de4d1c3dc3e.el7.centos
  ostree-grub2 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.a9cba0754ce8d81098afa850b25354634c28720c.el7.centos -> 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.c4dd042961eed840d10a08388d7a3de4d1c3dc3e.el7.centos
  ostree-libs 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.a9cba0754ce8d81098afa850b25354634c28720c.el7.centos -> 2017.10.9-19429b1a26d29c26e436ac34599897211fb6d86a.c4dd042961eed840d10a08388d7a3de4d1c3dc3e.el7.centos
  rpm-ostree 2017.8.6-ce2033c1821b70294bc85fb3c50046bb83143589.77767f7d8229c08232ae912753a435a981e115d9.el7.centos -> 2017.8.7-82f95e776104c33c3ee4c055aed5c16e4fa9e575.77767f7d8229c08232ae912753a435a981e115d9.el7.centos
  rpm-ostree-libs 2017.8.6-ce2033c1821b70294bc85fb3c50046bb83143589.77767f7d8229c08232ae912753a435a981e115d9.el7.centos -> 2017.8.7-82f95e776104c33c3ee4c055aed5c16e4fa9e575.77767f7d8229c08232ae912753a435a981e115d9.el7.cent
Run "systemctl reboot" to start a rebootos
```

**Comment by cgwalters** [comment]
Hmm...wait, this may be http://pkgs.fedoraproject.org/rpms/ostree/c/c4dd042961eed840d10a08388d7a3de4d1c3dc3e?branch=master

**Comment by jlebon** [comment]
Ahh very likely. Without the `%systemd_post` at compose time, the preset to enable it won't kick in, right?

**Comment by cgwalters** [comment]
For now https://src.fedoraproject.org/rpms/ostree/pull-request/3

**Comment by mike-nguyen** [comment]
Revert doesn't hurt :stuck_out_tongue_winking_eye:  https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/atomic-host-jobs-treecompose-improved-sanity-test-cahc/572/

**Comment by jlebon** [comment]
This is fixed in the latest image!
